-- Migration: Add guides and hotels tables
-- Run with: mysql -u root -p dillkash_kashmir < migration_guides_hotels.sql

USE `dillkash_kashmir`;

CREATE TABLE IF NOT EXISTS guides (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(100) NOT NULL,
  experience TINYINT UNSIGNED NOT NULL DEFAULT 1,
  bio TEXT,
  image_url TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hotels (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(255) NOT NULL,
  name VARCHAR(200) NOT NULL,
  location VARCHAR(100) NOT NULL,
  star_rating TINYINT UNSIGNED NOT NULL DEFAULT 3,
  price_per_night DECIMAL(10,2) NOT NULL DEFAULT 0,
  description TEXT,
  images JSON,
  amenities JSON,
  featured TINYINT(1) NOT NULL DEFAULT 0,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_hotel_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
